# Generated by Django 5.1.1 on 2024-09-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
